module info

    #######################################################################################
    # This module will contain many info about the language, stored in variables. #
    #######################################################################################

    symb_lst = ["+", "-", "*", "/", ".", "(", ")", "[", "]", "\"", "\'",
    "&", ",", "=", "!", "%", "^", ";", ":", "<", ">", " ", "\t", "#"] # Here are stored the Lazen one-char symbols
                                                                      # (except some that are generated by the compiler himself).

    op_lst = ["*", "+", "-", "/", "%", "^", "&", ",",
    "!", "=", ">", "<", "==", "!=", "<=", ">=", "+=",
    "/=", "*=", "-=", "^=", "%=", "&=", "@", "&&", "||",
    ":¨", "§§", "\$"] # Here is stored the Lazen operators list.

    ###########################################

end
